/*
 * @Author: 李国亮 
 * @Date: 2019-04-16 00:47:43 
 * @Last Modified by: 李国亮
 * @Last Modified time: 2019-05-31 18:43:11
 */

/************************* ACCOUNT ********************/
export const SET_USER_INFO = 'SET_USER_INFO'
export const LOGOUT = 'LOGOUT'


/************************* NEWS ********************/
export const GET_NEWS_BANNER = 'GET_NEWS_BANNER'
export const GET_MOST_HOT_NEWS = 'GET_MOST_HOT_NEWS'
export const GET_MOST_NEW_NEWS = 'GET_MOST_NEW_NEWS'
export const GET_MOST_HOT_TOPIC = 'GET_MOST_HOT_TOPIC'
export const GET_TA_NEWS_LIST = 'GET_TA_NEWS_LIST'
export const GET_MOST_NEWS_DETAIL = 'GET_MOST_NEWS_DETAIL'
export const GET_FOLLOW_LIST = 'GET_FOLLOW_LIST'
export const GET_LIKE_LIST = 'GET_LIKE_LIST'
export const SET_SHOW_MOST_HOT_NEWS = 'SET_SHOW_MOST_HOT_NEWS'
export const SET_KEYWORD_SEARCH = 'SET_KEYWORD_SEARCH'

/************************* COMMENT ********************/
export const GET_NEWS_COMMENT = "GET_NEWS_COMMENT"
export const ADD_NEWS_COMMENT = "ADD_NEWS_COMMENT"
export const ADD_NEWS_REPLY = "ADD_NEWS_REPLY"
export const ADD_NEWS_COMMENT_PAGEINDEX = "ADD_NEWS_COMMENT_PAGEINDEX"
export const CLEAR_NEWS_COMMENT = "CLEAR_NEWS_COMMENT"

/************************* SECONDHAND ********************/
export const GET_SECONDHAND_LIST = "GET_SECONDHAND_LIST"
export const GET_SECONDHAND_DETAIL = "GET_SECONDHAND_DETAIL"
export const SET_OPTIONS_MIN_PRICE = "SET_OPTIONS_MIN_PRICE"
export const SET_OPTIONS_MAX_PRICE = "SET_OPTIONS_MAX_PRICE"
export const SET_OPTIONS_PAGEINDEX = "SET_OPTIONS_PAGEINDEX"
export const SET_OPTIONS_KEYWORD = "SET_OPTIONS_KEYWORD"
export const GET_LIKE_SECONDHAND = "GET_LIKE_SECONDHAND"
export const GET_SECONDHAND_COMMENT_LIST = "GET_SECONDHAND_COMMENT_LIST"

/************************* ACTIVITY ********************/
export const GET_ACTIVITY_DETAIL = "GET_ACTIVITY_DETAIL"
export const GET_ACTIVITY_LIST = "GET_ACTIVITY_LIST"

/************************* PERSONAL ********************/
export const GET_PERSONAL_NEWS_LIST = "GET_PERSONAL_NEWS_LIST"
export const GET_ADMIN_NEWS_LIST = "GET_ADMIN_NEWS_LIST"
export const GET_PERSONAL_SECONDHAND_LIST = "GET_PERSONAL_SECONDHAND_LIST"
export const GET_ADMIN_SECONDHAND_LIST = "GET_ADMIN_SECONDHAND_LIST"
export const GET_PERSONAL_VIEW_LIST = "GET_PERSONAL_VIEW_LIST"
export const GET_PERSONAL_FOLLOW_LIST = "GET_PERSONAL_FOLLOW_LIST"
export const GET_PERSONAL_FAN_LIST = "GET_PERSONAL_FAN_LIST"
export const GET_PERSONAL_COLLECT_LIST = "GET_PERSONAL_COLLECT_LIST"
export const GET_ADMIN_REPORT_LIST = "GET_ADMIN_REPORT_LIST"
export const GET_ADMIN_FEEDBACK_LIST = "GET_ADMIN_FEEDBACK_LIST"
export const CLEAR_PERSONAL_NEWS_LIST = "CLEAR_PERSONAL_NEWS_LIST"
export const CLEAR_ADMIN_NEWS_LIST = "CLEAR_ADMIN_NEWS_LIST"
export const CLEAR_PERSONAL_SECONDHAND_LIST = "CLEAR_PERSONAL_SECONDHAND_LIST"
export const CLEAR_ADMIN_SECONDHAND_LIST = "CLEAR_ADMIN_SECONDHAND_LIST"
export const CLEAR_PERSONAL_VIEW_LIST = "CLEAR_PERSONAL_VIEW_LIST"
export const CLEAR_PERSONAL_FOLLOW_LIST = "CLEAR_PERSONAL_FOLLOW_LIST"
export const CLEAR_PERSONAL_FAN_LIST = "CLEAR_PERSONAL_FAN_LIST"
export const CLEAR_ADMIN_REPORT_LIST = "CLEAR_ADMIN_REPORT_LIST"
export const CLEAR_ADMIN_FEEDBACK_LIST = "CLEAR_ADMIN_FEEDBACK_LIST"
export const ADD_NEWS_PAGEINDEX = "ADD_NEWS_PAGEINDEX"
export const ADD_ADMIN_NEWS_PAGEINDEX = "ADD_ADMIN_NEWS_PAGEINDEX"
export const ADD_SECONDHAND_PAGEINDEX = "ADD_SECONDHAND_PAGEINDEX"
export const ADD_ADMIN_SECONDHAND_PAGEINDEX = "ADD_ADMIN_SECONDHAND_PAGEINDEX"
export const ADD_VIEW_PAGEINDEX = "ADD_VIEW_PAGEINDEX"
export const ADD_FOLLOW_PAGEINDEX = "ADD_FOLLOW_PAGEINDEX"
export const ADD_FAN_PAGEINDEX = "ADD_FAN_PAGEINDEX"
export const ADD_ADMIN_REPORT_PAGEINDEX = "ADD_ADMIN_REPORT_PAGEINDEX"
export const ADD_ADMIN_FEEDBACK_PAGEINDEX = "ADD_ADMIN_FEEDBACK_PAGEINDEX"





